name: Welcome
on:
  pull_request:
    types: [opened]
  issues:
    types: [opened]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/first-interaction@v1.2.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: |
            ğŸ‘‹ @{{ author }}
             Thanks for opening your first issue here! If you are reporting a bug, please make sure to include steps on how to reproduce it! :D

          pr-message: |
            ğŸ‘‹ @{{ author }}
            Thanks for opening this pull request! We will review it as soon as we can :3
            Please check out our contributing guidelines in the meantime.

         # FIRST_PR_MERGED: |
         #   ğŸ‰ @{{ author }}
         #   Congrats on getting your first pull request merged! We are proud of you :3 â¤ï¸
